### ISSUE TITLE
Generalize use case 1/2

### ISSUE THREAD

**Issue by CptTZ** [tsdb-project/influx-test#17]
User can adjust the parameters for them, like:
- Which period of time
- Which electrode

Add more if I miss something.

**Comment by CptTZ** [comment]
Probably fixed by https://github.com/tsdb-project/influx-test/commit/027963713048cc8afa6b59da6a138a075e9bf9aa

@isolachine Please close if it had been fixed

**Comment by isolachine** [comment]
Closed since no longer an issue.
