### ISSUE TITLE
Fully Functional Export Functionality

### ISSUE THREAD

**Issue by isolachine** [tsdb-project/influx-test#24]
Part of the export functionality has been hardcoded.
It's essential that this functionality is realized.

**Comment by isolachine** [comment]
[c64e604](https://github.com/tsdb-project/influx-test/commit/c64e6041450f532f3f0169d6e766b04aeeee5464) fixes the initial issue.

**Comment by isolachine** [comment]
@CptTZ Close on test pass.

**Comment by CptTZ** [comment]
A primitive test shows it worked well, will reopen once severe bugs noticed.
