### ISSUE TITLE
Backtracking Aggregation Group Columns

### ISSUE THREAD

**Issue by isolachine** [tsdb-project/influx-test#27]
This enhancement provides us the ability to view and edit column groups with less effort.
It will be done by turning the column data into multi-level JSON-like data.
A simple example would be like:
```
{
    "aEEG",
    ["Cz-Av17", "Pz-Av17"],
    ["Max", "Min"]
}
```

**Comment by isolachine** [comment]
This enhancement is a supplement of #26

**Comment by isolachine** [comment]
Seems like this functionality is fully usable right now. Closed.

**Comment by CptTZ** [comment]
Check ExportID `37`

**Comment by isolachine** [comment]
Closed on fix.
