### ISSUE TITLE
Patient Metadata Filtering

### ISSUE THREAD

**Issue by isolachine** [tsdb-project/influx-test#29]
This functionality should be implemented on both

- [ ] Status (Patient Info) Page
- [ ] Export Page

**Comment by isolachine** [comment]
Dynamic SQL Provided by MyBatis should be used in implementing this functionality.

Possible solutions are
- Extending Example Class http://www.mybatis.org/generator/generatedobjects/extendingExampleClass.html
- Using MyBatis Dynamic SQL Library
http://www.mybatis.org/mybatis-dynamic-sql/docs/quickStart.html
https://blog.olowolo.com/post/new-mybatis-dynamic-sql/

**Comment by CptTZ** [comment]
Not crucial to filter on properties of patients.
