### ISSUE TITLE
Time Zone Error on Output

### ISSUE THREAD

**Issue by isolachine** [tsdb-project/influx-test#42]
`output_meta.txt` seems to use UTC time for start time, need to be fixed

**Comment by isolachine** [comment]
@CptTZ Please change the output time to local time.

**Comment by CptTZ** [comment]
Fixed by https://github.com/tsdb-project/influx-test/commit/4d9c458d36604a66f1e74335a9e242d7bcbba887#diff-81ed3eb7d44a22fb7fbe69ed1c0e43f6R140
