### ISSUE TITLE
File lock and transfer mechanism

### ISSUE THREAD

**Issue by isolachine** [tsdb-project/influx-test#7]
**Implement functionality to better manage the import process.**
- Add a file lock upon start of import process to make sure only a single thread is operating each file
- Move finished files into a `finished` folder
- Move failed files into a `failed` folder

**Comment by CptTZ** [comment]
Updates:
- Won't move the **finished** files.

**Comment by CptTZ** [comment]
Most fixed by https://github.com/tsdb-project/influx-test/commit/61465295b656ef1cda84b842a0725f45888ba74f

Moving function not necessary.
